package com.knichu.domain.vo

data class LongRainCloudVO(
    val regionCode: String? = null,
    val rainProb3Am: Long? = null,
    val rainProb3Pm: Long? = null,
    val rainProb4Am: Long? = null,
    val rainProb4Pm: Long? = null,
    val rainProb5Am: Long? = null,
    val rainProb5Pm: Long? = null,
    val rainProb6Am: Long? = null,
    val rainProb6Pm: Long? = null,
    val rainProb7Am: Long? = null,
    val rainProb7Pm: Long? = null,
    val rainProb8: Long? = null,
    val rainProb9: Long? = null,
    val rainProb10: Long? = null,
    val weatherForecast3Am: String? = null,
    val weatherForecast3Pm: String? = null,
    val weatherForecast4Am: String? = null,
    val weatherForecast4Pm: String? = null,
    val weatherForecast5Am: String? = null,
    val weatherForecast5Pm: String? = null,
    val weatherForecast6Am: String? = null,
    val weatherForecast6Pm: String? = null,
    val weatherForecast7Am: String? = null,
    val weatherForecast7Pm: String? = null,
    val weatherForecast8: String? = null,
    val weatherForecast9: String? = null,
    val weatherForecast10: String? = null
)
